"""add api_spec to Product

Revision ID: 1abcf7a0c3ac
Revises: e622feabd4c9
Create Date: 2025-01-08 21:07:35.134523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1abcf7a0c3ac'
down_revision = 'e622feabd4c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_spec', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('api_spec')

    # ### end Alembic commands ###
