"""Add distributor_id and reward_percentage

Revision ID: 23f9f2949faa
Revises: 67a2c44a3abc
Create Date: 2025-01-13 23:21:23.738674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f9f2949faa'
down_revision = '67a2c44a3abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reward_percentage', sa.Float(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distributor_id', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['distributor_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('distributor_id')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('reward_percentage')

    # ### end Alembic commands ###
