"""Increase password_hash column length

Revision ID: 254c20e56493
Revises: 1abcf7a0c3ac
Create Date: 2025-01-10 16:06:23.249862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254c20e56493'
down_revision = '1abcf7a0c3ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
