"""Add distributor_id and reward_percentage fields

Revision ID: f7a739b74520
Revises: dc7997843f2c
Create Date: 2025-01-14 14:58:03.145088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a739b74520'
down_revision = 'dc7997843f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('distributor_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=36),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('distributor_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
